apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Con 1 Giga para desarrollo local sobra espacio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patitas-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: patitas-db
  template:
    metadata:
      labels:
        app: patitas-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Usamos la imagen oficial de MySQL
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root" # En producción usaríamos un Secret, acá para lab local va directo
        - name: MYSQL_DATABASE
          value: "patitas_felices" # Crea la base de datos automáticamente al iniciar
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql # Mapea la carpeta de datos de MySQL al disco local
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: patitas-db-service
  namespace: default
spec:
  ports:
    - port: 3306
  selector:
    app: patitas-db
